const app = document.querySelector('#app');
const state = { me: null, school: null, requests: [], timetable: [], users: [], notifications: [], resources: [], selected: null, messages: [] };
const esc = value => String(value ?? '').replace(/[&<>'"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[ch]));
const prettyDate = value => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${value.slice(0, 10)}T12:00:00`)) : '—';
const stamp = value => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value));
const dayName = value => ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][Number(value)] || 'Unscheduled';
const roleName = role => ({ admin: 'Administrator', teacher: 'Teacher', student: 'Student' }[role] || role);
const status = value => `<span class="status ${esc(value)}">${esc(value.replace('_', ' '))}</span>`;
async function api(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options, body: options.body && typeof options.body !== 'string' ? JSON.stringify(options.body) : options.body }); let body = {}; try { body = await response.json(); } catch {} if (!response.ok) { const err = new Error(body.error || 'The request could not be completed.'); err.details = body.details; throw err; } return body; }
function notice(message, kind = 'ok') { const node = document.createElement('div'); node.className = `notice ${kind}`; node.textContent = message; document.body.append(node); requestAnimationFrame(() => node.classList.add('visible')); setTimeout(() => { node.classList.remove('visible'); setTimeout(() => node.remove(), 250); }, 4200); }
function apiError(error) { const extra = Array.isArray(error.details) ? ` ${error.details.join(' ')}` : ''; notice(`${error.message}${extra}`, 'error'); }
function busy(button, value = true) { if (!button) return; button.disabled = value; button.dataset.original ??= button.innerHTML; button.innerHTML = value ? '<span class="spinner"></span> Working…' : button.dataset.original; }
function empty(title, copy, action = '') { return `<section class="empty"><div class="empty-icon">✦</div><h2>${esc(title)}</h2><p>${esc(copy)}</p>${action}</section>`; }
function modal(title, content, actions = '') { const node = document.createElement('div'); node.className = 'modal-wrap'; node.innerHTML = `<div class="scrim" data-close-modal></div><section class="modal" role="dialog" aria-modal="true"><button class="close" data-close-modal aria-label="Close">×</button><p class="eyebrow">HELIO</p><h2>${esc(title)}</h2><div class="modal-content">${content}</div>${actions ? `<footer>${actions}</footer>` : ''}</section>`; document.body.append(node); return node; }
function showRecovery(code, heading = 'Save your recovery code') { modal(heading, `<div class="recovery"><p>This is the only time Helio can show this code. Save it in a password manager; it can reset your password without email access.</p><code>${esc(code)}</code><button class="ghost" data-copy="${esc(code)}">Copy code</button></div>`, `<button class="primary" data-close-modal>I saved it securely</button>`); }

async function loadState() {
  const me = await api('/api/me'); state.me = me.user; state.school = me.school;
  const [requests, timetable, notifications, resources, users] = await Promise.all([api('/api/requests'), api('/api/timetable'), api('/api/notifications'), api('/api/resources'), state.me.role === 'admin' ? api('/api/users') : Promise.resolve({ users: [] })]);
  state.requests = requests.requests; state.timetable = timetable.entries; state.notifications = notifications.notifications; state.resources = resources.resources; state.users = users.users;
  if (!state.selected || !state.requests.some(r => r.id === state.selected)) state.selected = state.requests[0]?.id || null;
}
function authShell(inner) { app.innerHTML = `<main class="auth-shell"><section class="auth-panel"><a class="wordmark" href="/"> <span>h</span> helio</a><div class="auth-copy"><p class="eyebrow">SCHOOL OPERATIONS, IN SYNC</p><h1>Make the handover<br>feel <i>human.</i></h1><p>Leave, schedules, substitutions and the conversations around them—in one calm place.</p></div><div class="auth-trust"><span>✦</span> Humans keep the final say.</div></section><section class="auth-card">${inner}</section></main>`; }
async function start() { try { const bootstrap = await api('/api/bootstrap'); try { await loadState(); render(); } catch (error) { if (error.message.includes('sign in')) renderAuth(bootstrap.needsSetup ? 'setup' : 'login'); else throw error; } } catch (error) { app.innerHTML = `<main class="fatal"><h1>Helio couldn’t start</h1><p>${esc(error.message)}</p><button class="primary" onclick="location.reload()">Try again</button></main>`; } }
function renderAuth(view = 'login') {
  if (view === 'setup') return authShell(`<p class="eyebrow">FIRST, SET UP YOUR SCHOOL</p><h2>A calm start for everyone.</h2><p class="form-copy">Create the first administrator account. You’ll receive a school code to invite teachers and students.</p><form data-auth="setup"><label>Your name<input name="name" autocomplete="name" required></label><label>School name<input name="schoolName" required></label><label>Work email<input type="email" name="email" autocomplete="email" required></label><label>Secure password<input type="password" name="password" autocomplete="new-password" minlength="10" required><small>At least 10 characters.</small></label><button class="primary wide">Create school workspace <span>→</span></button></form><p class="auth-switch">Already set up? <button class="text-button" data-auth-view="login">Sign in</button></p>`);
  if (view === 'signup') return authShell(`<p class="eyebrow">JOIN YOUR SCHOOL</p><h2>Find your place in the flow.</h2><p class="form-copy">Your school administrator can share the join code.</p><form data-auth="signup"><label>Full name<input name="name" autocomplete="name" required></label><label>School code<input name="joinCode" autocomplete="off" required></label><label>Role<select name="role"><option value="teacher">Teacher</option><option value="student">Student</option></select></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="new-password" minlength="10" required></label><button class="primary wide">Create account <span>→</span></button></form><p class="auth-switch">Have an account? <button class="text-button" data-auth-view="login">Sign in</button></p>`);
  if (view === 'recover') return authShell(`<p class="eyebrow">ACCOUNT RECOVERY</p><h2>Use your saved recovery code.</h2><p class="form-copy">Recovery codes are given when an account is created. Your administrator can also issue a new account if a code is lost.</p><form data-auth="recover"><label>Email<input type="email" name="email" required></label><label>Recovery code<input name="recoveryCode" required></label><label>New password<input type="password" name="password" minlength="10" required></label><button class="primary wide">Reset password <span>→</span></button></form><p class="auth-switch"><button class="text-button" data-auth-view="login">Back to sign in</button></p>`);
  return authShell(`<p class="eyebrow">WELCOME BACK</p><h2>Good to see you.</h2><p class="form-copy">Sign in to pick up where your school left off.</p><form data-auth="login"><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="primary wide">Sign in <span>→</span></button></form><p class="auth-switch"><button class="text-button" data-auth-view="signup">Join a school</button><span>·</span><button class="text-button" data-auth-view="recover">Recover account</button></p>`);
}

function navItem(route, icon, label, badge = '') { return `<a href="#${route}" class="${location.hash.slice(1) === route || (!location.hash && route === 'home') ? 'active' : ''}"><span>${icon}</span>${label}${badge}</a>`; }
function shell(content) { const route = location.hash.slice(1) || 'home'; const unread = state.notifications.filter(n => !n.readAt).length; const role = state.me.role; const initials = state.me.name.split(/\s+/).map(v => v[0]).slice(0, 2).join('').toUpperCase(); app.innerHTML = `<aside class="sidebar"><a class="wordmark" href="#home"><span>h</span> helio</a><div class="school-switch"><div class="school-glyph">${esc(state.school.name[0] || 'S')}</div><div><b>${esc(state.school.name)}</b><small>${roleName(role)} workspace</small></div></div><nav>${navItem('home', '◫', 'Overview')}${navItem('leave', '＋', 'Request leave')}${navItem('requests', '◷', 'My requests')}${navItem('schedule', '▦', 'Schedule')}${navItem('resources', '▤', 'Resources')}${role === 'admin' ? navItem('review', '✓', 'Coverage review', state.requests.filter(r => ['submitted', 'in_review'].includes(r.status)).length ? `<b>${state.requests.filter(r => ['submitted', 'in_review'].includes(r.status)).length}</b>` : '') : ''}${role === 'admin' ? navItem('people', '◉', 'People') : ''}</nav><div class="sidebar-bottom"><a href="#profile"><span>⚙</span> Profile & availability</a><button class="user-card" data-action="logout"><span class="avatar">${initials}</span><span><b>${esc(state.me.name)}</b><small>${roleName(role)}</small></span><i>↗</i></button></div></aside><main class="workspace"><header class="topbar"><div class="crumb">${esc(state.school.name)} <span>/</span> ${esc(route === 'home' ? 'Overview' : route.replace('-', ' '))}</div><div class="top-actions"><button class="bell" data-action="notifications" aria-label="Notifications">♧${unread ? `<i>${unread > 9 ? '9+' : unread}</i>` : ''}</button><button class="avatar" data-route="profile">${initials}</button></div></header><div class="page">${content}</div></main>`; }
function pageHeading(kicker, title, copy, action = '') { return `<section class="heading"><div><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1><p>${esc(copy)}</p></div>${action}</section>`; }
function requestRow(r, interactive = true) { const requester = r.requester?.name || 'Unknown requester'; return `<article class="request-row ${r.id === state.selected ? 'selected' : ''}" ${interactive ? `data-request="${r.id}"` : ''}><div class="request-pip ${esc(r.status)}"></div><div><b>${esc(requester)}</b><p>${esc(r.startDate === r.endDate ? prettyDate(r.startDate) : `${prettyDate(r.startDate)} – ${prettyDate(r.endDate)}`)} · ${esc(r.requesterRole)} leave</p></div>${status(r.status)}<span class="arrow">›</span></article>`; }
function dashboard() { const active = state.requests.filter(r => ['submitted', 'in_review', 'approved'].includes(r.status)); const today = new Date().getDay(); const todayClasses = state.timetable.filter(e => Number(e.day) === today).sort((a, b) => a.start.localeCompare(b.start)); const review = state.me.role === 'admin' ? state.requests.filter(r => ['submitted', 'in_review'].includes(r.status)) : active; const classes = todayClasses.length ? `<div class="today-list">${todayClasses.map(e => `<article><time>${esc(e.start)}<small>${esc(e.end)}</small></time><span class="subject-bar"></span><div><b>${esc(e.className)}</b><p>${esc(e.subject)}${e.room ? ` · ${esc(e.room)}` : ''}</p></div></article>`).join('')}</div>` : empty('No classes scheduled today', 'When a timetable is imported, today’s classes will appear here.'); shell(`${pageHeading('YOUR WORKSPACE', `Welcome, ${state.me.name.split(' ')[0]}.`, 'The parts that need you are gathered here.', `<a class="primary" href="#leave">Request leave <span>→</span></a>`)}<section class="metric-grid"><article><small>${state.me.role === 'admin' ? 'NEEDS REVIEW' : 'ACTIVE REQUESTS'}</small><strong>${review.length}</strong><p>${review.length === 1 ? 'request needs attention' : 'requests need attention'}</p></article><article><small>CLASSES TODAY</small><strong>${todayClasses.length}</strong><p>from your current timetable</p></article><article><small>UNREAD UPDATES</small><strong>${state.notifications.filter(n => !n.readAt).length}</strong><p>kept in one place</p></article></section><section class="dashboard-columns"><section class="glass-card"><div class="section-title"><div><p class="eyebrow">TODAY</p><h2>Your schedule</h2></div><a href="#schedule">Open schedule →</a></div>${classes}</section><section class="glass-card"><div class="section-title"><div><p class="eyebrow">${state.me.role === 'admin' ? 'COVERAGE QUEUE' : 'REQUEST UPDATES'}</p><h2>${state.me.role === 'admin' ? 'Ready for a decision' : 'Leave at a glance'}</h2></div><a href="#${state.me.role === 'admin' ? 'review' : 'requests'}">View all →</a></div>${review.length ? `<div class="request-list">${review.slice(0, 4).map(r => requestRow(r)).join('')}</div>` : empty('All clear.', 'New requests and coverage changes will appear here.')}</section></section>`); }
function leavePage() { const noTimetable = !state.timetable.length; shell(`${pageHeading('LEAVE REQUEST', 'A clear handover starts here.', 'Your scheduled classes are found automatically. You only need to tell us when and why.')}${noTimetable ? empty('No timetable found', 'A request cannot identify affected classes until an administrator imports your timetable.', state.me.role === 'admin' ? '<a class="primary" href="#schedule">Manage timetable</a>' : '') : `<section class="form-card"><div class="form-intro"><span class="big-orb">✦</span><h2>We’ll do the schedule work.</h2><p>Helio checks your timetable, finds affected classes, and—when a teacher is away—ranks eligible cover without breaking existing schedules.</p></div><form data-form="leave"><div class="field-row"><label>Start date<input type="date" name="startDate" required></label><label>End date<input type="date" name="endDate" required></label></div><label>Reason <small>Optional — visible to administrators</small><textarea name="reason" placeholder="Add context that helps your school respond thoughtfully."></textarea></label><label>Supporting information <small>Optional</small><textarea name="supportingInfo" placeholder="Anything a teacher or administrator should know?"></textarea></label><div class="form-actions"><span>Classes and relevant staff will be identified from the timetable.</span><button class="primary">Send request <span>→</span></button></div></form></section>`}`); }
function requestsPage() { shell(`${pageHeading('REQUEST HISTORY', 'Your leave requests', 'Every update, decision and conversation stays connected to its request.', '<a class="primary" href="#leave">New request <span>＋</span></a>')}${state.requests.length ? `<section class="request-table">${state.requests.map(r => requestRow(r)).join('')}</section>` : empty('No leave requests yet', 'When you need time away, Helio will make the handover visible to the right people.', '<a class="primary" href="#leave">Request leave</a>')}`); }
function assignmentName(a) { return state.users.find(u => u.id === a.teacherId)?.name || 'Assigned teacher'; }
function reviewPage() { if (state.me.role !== 'admin') return shell(`${pageHeading('COVERAGE REVIEW', 'Permission required', 'Only administrators can resolve coverage plans.')}`); const r = state.requests.find(x => x.id === state.selected); const details = r ? r.recommendations || [] : []; const requestList = state.requests.length ? `<aside class="review-list">${state.requests.map(x => requestRow(x)).join('')}</aside>` : '';
  const detail = !r ? empty('No requests to review', 'New leave requests will arrive here with their schedule context.') : `<section class="review-detail glass-card"><div class="review-top"><div><p class="eyebrow">REQUEST ${esc(r.id.slice(-8).toUpperCase())}</p><h2>${esc(r.requester?.name || 'Requester')} · ${prettyDate(r.startDate)}${r.endDate !== r.startDate ? ` – ${prettyDate(r.endDate)}` : ''}</h2><p>${esc(r.reason || 'No reason added.')}</p></div>${status(r.status)}</div><div class="coverage-summary"><span>✦</span><div><b>Schedule-aware recommendations</b><p>Only teachers with no timetable, availability or cover-limit conflict appear below. Subject fit influences ranking, but never overrides those hard constraints.</p></div><button class="ghost" data-action="refresh-recs" data-id="${r.id}">Refresh</button></div><div class="coverage-items">${details.map(item => { const assigned = r.assignments?.filter(a => a.entryId === item.entryId) || []; return `<article><div class="class-context"><span class="subject-dot"></span><div><b>${esc(item.className)} · ${esc(item.subject)}</b><p>${dayName(item.day)} · ${esc(item.start)}–${esc(item.end)}${item.room ? ` · ${esc(item.room)}` : ''}</p></div></div>${item.warnings?.length ? `<div class="warning">${esc(item.warnings.join(' '))}</div>` : `<div class="candidate-list">${item.candidates.map((c, index) => `<div class="candidate"><div><b>${esc(c.name)}</b>${index === 0 ? '<span class="best">Best fit</span>' : ''}<p>${c.reasons.map(esc).join(' · ')}</p></div><strong>${c.score}<small>/100</small></strong>${assigned.some(a => a.teacherId === c.teacherId) ? '<span class="assigned">Assigned</span>' : `<button class="small-primary" data-action="assign" data-request="${r.id}" data-entry="${item.entryId}" data-teacher="${c.teacherId}">Assign</button>`}</div>`).join('')}</div>`}</article>`; }).join('') || empty('Recommendations unavailable', 'Refresh recommendations after timetable or availability changes.')} </div><section class="discussion"><div class="section-title"><div><p class="eyebrow">REQUEST DISCUSSION</p><h3>Keep the context together</h3></div></div><div class="messages">${state.messages.length ? state.messages.map(m => `<article class="message ${m.authorId === state.me.id ? 'mine' : ''}"><b>${esc(m.author?.name || 'Member')}</b><p>${esc(m.text)}</p><small>${stamp(m.createdAt)}</small></article>`).join('') : '<p class="quiet">No messages yet. Start the practical conversation here.</p>'}</div><form class="message-form" data-form="message" data-request="${r.id}"><input name="text" maxlength="2000" placeholder="Message the people involved…" required><button class="primary">Send</button></form></section><div class="decision-bar"><button class="secondary" data-action="resolve" data-status="rejected" data-id="${r.id}">Reject request</button><button class="primary" data-action="resolve" data-status="approved" data-id="${r.id}">Approve coverage plan <span>→</span></button></div></section>`;
  shell(`${pageHeading('COVERAGE MANAGEMENT', 'Review with context.', 'Recommendations are ranked, explainable and always subject to your decision.')}${state.requests.length ? `<section class="review-grid">${requestList}${detail}</section>` : empty('The coverage queue is clear', 'When someone submits leave, its timetable context and eligible covers will appear here.')}`); }
function schedulePage() { const entries = [...state.timetable].sort((a, b) => Number(a.day) - Number(b.day) || a.start.localeCompare(b.start)); const people = state.users; const schedule = entries.length ? `<div class="schedule-list">${entries.map(e => `<article><span class="day-token">${esc(dayName(e.day).slice(0, 3))}</span><time>${esc(e.start)}<small>${esc(e.end)}</small></time><div><b>${esc(e.className)}</b><p>${esc(e.subject)}${e.room ? ` · ${esc(e.room)}` : ''}</p></div>${state.me.role === 'admin' ? `<small class="owner">${esc(people.find(u => u.id === e.teacherId)?.name || 'Teacher')}</small>` : ''}</article>`).join('')}</div>` : empty('No timetable entries yet', state.me.role === 'admin' ? 'Import a timetable or add a class to make schedules and substitutions work.' : 'Your administrator has not associated any timetable entries with your account yet.');
  const controls = state.me.role === 'admin' ? `<div class="heading-actions"><button class="secondary" data-action="import">Import CSV</button><button class="primary" data-action="add-class">Add class <span>＋</span></button></div>` : '';
  shell(`${pageHeading('TIMETABLE', 'The source of a smoother day.', 'Classes here drive conflict detection, affected leave and substitute eligibility.', controls)}<section class="glass-card">${schedule}</section>`); }
function resourcesPage() { const entries = state.resources; const cards = entries.length ? `<section class="resource-grid">${entries.map(r => `<article class="resource-card"><span class="resource-type">${esc(r.mime.split('/').pop().toUpperCase())}</span><h3>${esc(r.name)}</h3><p>${esc(r.className || 'Shared school resource')}</p><footer><span>${stamp(r.createdAt)}</span><a href="/api/resources/${r.id}">Download</a></footer></article>`).join('')}</section>` : empty('Your shared library is empty', 'Upload practical, ready-to-use materials so the right person has them when cover changes.');
  const action = ['teacher', 'admin'].includes(state.me.role) ? '<button class="primary" data-action="upload">Upload resource <span>＋</span></button>' : '';
  shell(`${pageHeading('RESOURCES', 'Resources that travel with the work.', 'Files are available to colleagues in your school and ready for practical handovers.', action)}${cards}`); }
function peoplePage() { if (state.me.role !== 'admin') return shell(''); const users = state.users; shell(`${pageHeading('PEOPLE', 'The people behind the plan.', `Invite and maintain the roles that make ${state.school.name} run well.`, '<button class="primary" data-action="add-person">Add person <span>＋</span></button>')}<section class="split-admin"><div class="glass-card"><div class="section-title"><h2>School access</h2><button class="ghost" data-copy="${esc(state.school.joinCode)}">Copy join code</button></div><div class="join-code"><span>${esc(state.school.joinCode)}</span><p>Teachers and students use this code when they join.</p></div></div><div class="glass-card"><div class="section-title"><h2>Cover guardrail</h2></div><form data-form="cover-limit" class="inline-form"><label>Maximum cover assignments<input type="number" name="maxWeeklyCover" min="1" value="${state.school.maxWeeklyCover}"></label><button class="primary">Save</button></form></div></section><section class="people-list">${users.map(u => `<article><span class="avatar">${esc(u.name.split(/\s+/).map(v => v[0]).slice(0, 2).join(''))}</span><div><b>${esc(u.name)}</b><p>${esc(u.email)}</p></div><span class="role-pill">${esc(roleName(u.role))}</span></article>`).join('')}</section>`); }
function profilePage() { const p = state.me.preferences || {}; shell(`${pageHeading('PROFILE & AVAILABILITY', 'Set the context Helio should respect.', 'Availability is a hard constraint. Subject and grade experience can improve a recommendation, but will never override a conflict.')}<section class="form-card profile-card"><form data-form="profile"><label>Name<input name="name" value="${esc(state.me.name)}" required></label><label>Subjects you’re comfortable covering <small>Comma separated</small><input name="subjects" value="${esc((p.subjects || []).join(', '))}" placeholder="e.g. Science, English"></label><label>Grades you’re comfortable covering <small>Comma separated</small><input name="grades" value="${esc((p.grades || []).join(', '))}" placeholder="e.g. 7, 8, 9"></label><label>Unavailable dates <small>Comma separated YYYY-MM-DD dates</small><input name="unavailableDates" value="${esc((p.unavailableDates || []).join(', '))}" placeholder="e.g. 2026-09-18, 2026-09-21"></label><div class="form-actions"><span>Changes take effect immediately in coverage checks.</span><button class="primary">Save profile</button></div></form></section><section class="security-card"><h2>Password</h2><p>Use a unique password with at least 10 characters.</p><button class="secondary" data-action="password">Change password</button></section>`); }
function notificationsModal() { const list = state.notifications; modal('Your updates', list.length ? `<div class="notification-list">${list.map(n => `<article class="${n.readAt ? '' : 'new'}"><b>${esc(n.body)}</b><small>${stamp(n.createdAt)}</small>${n.requestId ? `<a href="#${state.me.role === 'admin' ? 'review' : 'requests'}" data-open-request="${n.requestId}">Open request →</a>` : ''}</article>`).join('')}</div>` : '<p class="quiet">You’re all caught up.</p>', '<button class="secondary" data-action="read-notifications">Mark all read</button><button class="primary" data-close-modal>Done</button>'); }
function requestDetailPage() { const r = state.requests.find(x => x.id === state.selected); if (!r) return requestsPage(); const classes = r.affectedEntries?.length ? r.affectedEntries.map(e => `<article class="class-context"><span class="subject-dot"></span><div><b>${esc(e.className)} · ${esc(e.subject)}</b><p>${dayName(e.day)} · ${esc(e.start)}–${esc(e.end)}${e.room ? ` · ${esc(e.room)}` : ''}</p></div></article>`).join('') : '<p class="quiet">No affected classes were recorded.</p>'; const covers = r.assignments?.length ? r.assignments.map(a => `<article class="cover-line"><b>${esc(a.className)}</b><span>${esc(a.teacher?.name || 'Assigned teacher')} · ${prettyDate(a.date)}</span></article>`).join('') : '<p class="quiet">No cover assignment is required or confirmed yet.</p>'; shell(`${pageHeading('LEAVE REQUEST', 'Request detail', 'Everything about this leave request stays together.', '<a class="secondary" href="#requests">Back to requests</a>')}<section class="request-detail-layout"><section class="glass-card"><div class="review-top"><div><p class="eyebrow">SUBMITTED ${stamp(r.createdAt)}</p><h2>${prettyDate(r.startDate)}${r.endDate !== r.startDate ? ` – ${prettyDate(r.endDate)}` : ''}</h2><p>${esc(r.reason || 'No reason provided.')}</p></div>${status(r.status)}</div><div class="detail-section"><p class="eyebrow">AFFECTED CLASSES</p>${classes}</div><div class="detail-section"><p class="eyebrow">COVERAGE</p>${covers}</div>${r.resolutionNote ? `<div class="resolution"><b>Decision note</b><p>${esc(r.resolutionNote)}</p></div>` : ''}</section><section class="glass-card discussion"><div class="section-title"><div><p class="eyebrow">REQUEST DISCUSSION</p><h3>Practical details, in context</h3></div></div><div class="messages">${state.messages.length ? state.messages.map(m => `<article class="message ${m.authorId === state.me.id ? 'mine' : ''}"><b>${esc(m.author?.name || 'Member')}</b><p>${esc(m.text)}</p><small>${stamp(m.createdAt)}</small></article>`).join('') : '<p class="quiet">No messages yet. Use this thread for the handover details.</p>'}</div><form class="message-form" data-form="message" data-request="${r.id}"><input name="text" maxlength="2000" placeholder="Share a practical update…" required><button class="primary">Send</button></form></section></section>`); }
function render() { const route = location.hash.slice(1) || 'home'; if (route === 'leave') leavePage(); else if (route === 'requests') requestsPage(); else if (route === 'request') requestDetailPage(); else if (route === 'review') reviewPage(); else if (route === 'schedule') schedulePage(); else if (route === 'resources') resourcesPage(); else if (route === 'people') peoplePage(); else if (route === 'profile') profilePage(); else dashboard(); }
async function openRequest(id) { state.selected = id; const detail = await api(`/api/requests/${id}`); state.messages = detail.messages; location.hash = state.me.role === 'admin' ? 'review' : 'request'; render(); }
function addClassModal() { const teachers = state.users.filter(u => ['teacher', 'admin'].includes(u.role)); const students = state.users.filter(u => u.role === 'student'); modal('Add a timetable class', `<form id="class-form"><div class="field-row"><label>Day<select name="day">${['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((d, i) => `<option value="${i}">${d}</option>`).join('')}</select></label><label>Teacher<select name="teacherId" required>${teachers.map(u => `<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label></div><div class="field-row"><label>Start<input type="time" name="start" required></label><label>End<input type="time" name="end" required></label></div><label>Class<input name="className" required></label><label>Subject<input name="subject" required></label><label>Room<input name="room"></label><label>Student <small>Optional; this associates the class with a student’s leave workflow.</small><select name="studentId"><option value="">No student association</option>${students.map(u => `<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label></form>`, '<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="save-class">Add class</button>'); }
function importModal() { modal('Import timetable CSV', `<p class="form-copy">Required columns: <code>day,start,end,class,subject,teacher_email</code>. Optional columns: <code>room,student_email</code>. Day uses 0 for Sunday through 6 for Saturday. Time uses 24-hour HH:MM.</p><label class="file-picker">Choose CSV file<input id="csv-file" type="file" accept=".csv,text/csv"></label><p class="quiet">The import validates staff emails, dates, time formats, and every teacher conflict before saving anything.</p>`, '<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="save-import">Validate and import</button>'); }
function uploadModal() { modal('Upload a resource', `<form id="resource-form"><label>Resource name<input name="name" required></label><label>Class or use <input name="className" placeholder="e.g. Grade 8 science"></label><label class="file-picker">Choose file<input name="file" type="file" required></label><p class="quiet">Files are stored privately within your school workspace. Maximum upload size: 4 MB.</p></form>`, '<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="save-resource">Upload</button>'); }
function personModal() { modal('Create a school account', `<form id="person-form"><label>Full name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Role<select name="role"><option value="teacher">Teacher</option><option value="student">Student</option><option value="admin">Administrator</option></select></label><label>Temporary password<input type="password" name="password" minlength="10" required></label><p class="quiet">The account holder will receive a recovery code once. Share it securely with them.</p></form>`, '<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="save-person">Create account</button>'); }
async function handleAction(event) { const button = event.target.closest('[data-action]'); if (!button) return; const action = button.dataset.action; try {
  if (action === 'logout') { busy(button); await api('/api/auth/logout', { method: 'POST' }); state.me = null; renderAuth('login'); return; }
  if (action === 'notifications') return notificationsModal();
  if (action === 'read-notifications') { busy(button); await api('/api/notifications/read', { method: 'POST' }); await loadState(); document.querySelector('.modal-wrap')?.remove(); render(); notice('Notifications marked as read.'); return; }
  if (action === 'refresh-recs') { busy(button); await api(`/api/requests/${button.dataset.id}/recommendations`, { method: 'POST' }); await loadState(); await openRequest(button.dataset.id); notice('Recommendations refreshed against the latest schedule.'); return; }
  if (action === 'assign') { busy(button); await api(`/api/requests/${button.dataset.request}/assignment`, { method: 'POST', body: { entryId: button.dataset.entry, teacherId: button.dataset.teacher } }); await loadState(); await openRequest(button.dataset.request); notice('Cover assigned and the teacher has been notified.'); return; }
  if (action === 'resolve') { const request = state.requests.find(r => r.id === button.dataset.id); modal(button.dataset.status === 'approved' ? 'Approve this leave request?' : 'Reject this leave request?', `<label>Decision note <small>Optional, shared with the requester</small><textarea id="decision-note" placeholder="Add context for the decision."></textarea></label>`, `<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="confirm-resolution" data-id="${request.id}" data-status="${button.dataset.status}">${button.dataset.status === 'approved' ? 'Approve' : 'Reject'}</button>`); return; }
  if (action === 'confirm-resolution') { busy(button); await api(`/api/requests/${button.dataset.id}/decision`, { method: 'POST', body: { status: button.dataset.status, note: document.querySelector('#decision-note')?.value || '' } }); document.querySelector('.modal-wrap')?.remove(); await loadState(); state.messages = []; render(); notice(`Request ${button.dataset.status}. Everyone relevant has been updated.`); return; }
  if (action === 'import') return importModal(); if (action === 'add-class') return addClassModal(); if (action === 'upload') return uploadModal(); if (action === 'add-person') return personModal();
  if (action === 'save-class') { const form = document.querySelector('#class-form'), data = Object.fromEntries(new FormData(form)); data.studentIds = data.studentId ? [data.studentId] : []; busy(button); await api('/api/timetable', { method: 'POST', body: data }); document.querySelector('.modal-wrap')?.remove(); await loadState(); render(); notice('Class added. It is now included in conflict checks.'); return; }
  if (action === 'save-import') { const file = document.querySelector('#csv-file')?.files[0]; if (!file) throw new Error('Choose a CSV file to import.'); busy(button); const csv = await file.text(); const result = await api('/api/timetable/import', { method: 'POST', body: { csv } }); document.querySelector('.modal-wrap')?.remove(); await loadState(); render(); notice(`${result.imported} timetable ${result.imported === 1 ? 'entry' : 'entries'} imported.`); return; }
  if (action === 'save-resource') { const form = document.querySelector('#resource-form'), data = new FormData(form), file = data.get('file'); if (!file?.size) throw new Error('Choose a file to upload.'); if (file.size > 4_000_000) throw new Error('Choose a file smaller than 4 MB.'); busy(button); const encoded = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); await api('/api/resources', { method: 'POST', body: { name: data.get('name') || file.name, className: data.get('className'), data: encoded } }); document.querySelector('.modal-wrap')?.remove(); await loadState(); render(); notice('Resource uploaded to your school workspace.'); return; }
  if (action === 'save-person') { const data = Object.fromEntries(new FormData(document.querySelector('#person-form'))); busy(button); const result = await api('/api/users', { method: 'POST', body: data }); document.querySelector('.modal-wrap')?.remove(); await loadState(); render(); showRecovery(result.recoveryCode, `Recovery code for ${result.user.name}`); return; }
  if (action === 'password') return modal('Change your password', `<form id="password-form"><label>Current password<input type="password" name="currentPassword" required></label><label>New password<input type="password" name="newPassword" minlength="10" required></label></form>`, '<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-action="save-password">Update password</button>');
  if (action === 'save-password') { busy(button); await api('/api/me', { method: 'PATCH', body: Object.fromEntries(new FormData(document.querySelector('#password-form'))) }); document.querySelector('.modal-wrap')?.remove(); notice('Your password has been updated.'); return; }
} catch (error) { apiError(error); busy(button, false); } }
async function handleForm(event) { const form = event.target; if (!form.matches('form')) return; event.preventDefault(); const mode = form.dataset.auth; try { if (mode) { const button = form.querySelector('button'); busy(button); const data = Object.fromEntries(new FormData(form)); if (mode === 'recover') { await api('/api/auth/recover', { method: 'POST', body: data }); renderAuth('login'); notice('Password reset. Sign in with your new password.'); return; } const endpoint = mode === 'setup' ? '/api/auth/setup' : mode === 'signup' ? '/api/auth/signup' : '/api/auth/login'; const result = await api(endpoint, { method: 'POST', body: data }); if (result.recoveryCode) { await loadState(); render(); showRecovery(result.recoveryCode); } else { await loadState(); render(); } return; }
  if (form.dataset.form === 'leave') { const button = form.querySelector('button'); busy(button); const result = await api('/api/requests', { method: 'POST', body: Object.fromEntries(new FormData(form)) }); await loadState(); state.selected = result.request.id; state.messages = []; location.hash = state.me.role === 'admin' ? 'review' : 'requests'; render(); notice('Leave request submitted. The right people have been notified.'); return; }
  if (form.dataset.form === 'message') { const button = form.querySelector('button'); busy(button); const result = await api(`/api/requests/${form.dataset.request}/messages`, { method: 'POST', body: Object.fromEntries(new FormData(form)) }); state.messages.push(result.message); form.reset(); render(); return; }
  if (form.dataset.form === 'profile') { const data = Object.fromEntries(new FormData(form)); data.preferences = { subjects: data.subjects.split(',').map(v => v.trim()).filter(Boolean), grades: data.grades.split(',').map(v => v.trim()).filter(Boolean), unavailableDates: data.unavailableDates.split(',').map(v => v.trim()).filter(v => /^\d{4}-\d{2}-\d{2}$/.test(v)) }; const button = form.querySelector('button'); busy(button); await api('/api/me', { method: 'PATCH', body: data }); await loadState(); render(); notice('Profile and availability saved.'); return; }
  if (form.dataset.form === 'cover-limit') { const button = form.querySelector('button'); busy(button); await api('/api/school', { method: 'PATCH', body: Object.fromEntries(new FormData(form)) }); await loadState(); render(); notice('Cover guardrail saved. New recommendations will respect it.'); }
} catch (error) { apiError(error); busy(form.querySelector('button'), false); } }
document.addEventListener('click', async event => { const close = event.target.closest('[data-close-modal]'); if (close) { document.querySelector('.modal-wrap')?.remove(); return; } const view = event.target.closest('[data-auth-view]'); if (view) return renderAuth(view.dataset.authView); const copy = event.target.closest('[data-copy]'); if (copy) { await navigator.clipboard?.writeText(copy.dataset.copy); notice('Copied to clipboard.'); return; } const request = event.target.closest('[data-request]'); if (request) { try { await openRequest(request.dataset.request); } catch (error) { apiError(error); } return; } const open = event.target.closest('[data-open-request]'); if (open) { document.querySelector('.modal-wrap')?.remove(); try { await openRequest(open.dataset.openRequest); } catch (error) { apiError(error); } return; } const route = event.target.closest('[data-route]'); if (route) { location.hash = route.dataset.route; return; } handleAction(event); });
document.addEventListener('submit', handleForm); window.addEventListener('hashchange', () => state.me && render());
setInterval(async () => { if (!state.me || document.hidden) return; try { await loadState(); if (state.selected) { const detail = await api(`/api/requests/${state.selected}`); state.messages = detail.messages; } if (!document.querySelector('.modal-wrap')) render(); } catch {} }, 30000);
start();
