import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const dataDir = process.env.HELIO_DATA_DIR ? path.resolve(process.env.HELIO_DATA_DIR) : path.join(root, 'data');
const uploadsDir = path.join(dataDir, 'uploads');
const dbFile = path.join(dataDir, 'store.json');
fs.mkdirSync(uploadsDir, { recursive: true });
const emptyDb = () => ({ schools: [], users: [], sessions: [], timetable: [], requests: [], messages: [], notifications: [], resources: [] });
let db = fs.existsSync(dbFile) ? JSON.parse(fs.readFileSync(dbFile, 'utf8')) : emptyDb();
for (const key of Object.keys(emptyDb())) db[key] ??= [];
const save = () => fs.writeFileSync(dbFile, JSON.stringify(db, null, 2));
const id = (prefix = '') => `${prefix}${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const clean = value => String(value ?? '').trim();
const hash = (value, salt = crypto.randomBytes(16).toString('hex')) => ({ salt, value: crypto.pbkdf2Sync(value, salt, 210000, 32, 'sha256').toString('hex') });
const verify = (value, stored) => crypto.timingSafeEqual(Buffer.from(hash(value, stored.salt).value, 'hex'), Buffer.from(stored.value, 'hex'));
const recovery = () => crypto.randomBytes(12).toString('base64url');
const parseCookies = req => Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(v => v.trim().split('=')));
const safeUser = user => ({ id: user.id, schoolId: user.schoolId, name: user.name, email: user.email, role: user.role, recoverySet: Boolean(user.recoveryHash), preferences: user.preferences || {}, createdAt: user.createdAt });
const json = (res, code, body) => { res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(body)); };
const error = (res, code, message, details) => json(res, code, { error: message, details });
const readBody = req => new Promise((resolve, reject) => { let value = ''; req.on('data', part => { value += part; if (value.length > 7_000_000) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(value ? JSON.parse(value) : {}); } catch { reject(new Error('Invalid JSON')); } }); });
function currentUser(req) { const token = parseCookies(req).helio_session; const session = db.sessions.find(s => s.token === token && new Date(s.expiresAt) > new Date()); return session && db.users.find(u => u.id === session.userId); }
function requireUser(req, res, roles) { const user = currentUser(req); if (!user) { error(res, 401, 'Please sign in to continue.'); return null; } if (roles && !roles.includes(user.role)) { error(res, 403, 'You do not have permission for that action.'); return null; } return user; }
function createSession(res, user) { const token = crypto.randomBytes(32).toString('base64url'); db.sessions = db.sessions.filter(s => s.userId !== user.id && new Date(s.expiresAt) > new Date()); db.sessions.push({ token, userId: user.id, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString() }); save(); res.setHeader('Set-Cookie', `helio_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600`); }
function schoolFor(user) { return db.schools.find(s => s.id === user.schoolId); }
function notify(userIds, type, body, requestId = null) { for (const userId of new Set(userIds.filter(Boolean))) db.notifications.unshift({ id: id('n_'), userId, type, body, requestId, readAt: null, createdAt: now() }); }
const rangesOverlap = (aStart, aEnd, bStart, bEnd) => aStart < bEnd && bStart < aEnd;
function weekday(date) { return new Date(`${date}T12:00:00`).getDay(); }
function datesBetween(start, end) { const out = []; for (let d = new Date(`${start}T12:00:00`), last = new Date(`${end}T12:00:00`); d <= last; d.setDate(d.getDate() + 1)) out.push(d.toISOString().slice(0, 10)); return out; }
function scheduleForUser(user, from, to) { const dates = datesBetween(from, to); return db.timetable.filter(e => e.schoolId === user.schoolId && dates.some(d => weekday(d) === Number(e.day)) && (user.role === 'admin' || e.teacherId === user.id || (e.studentIds || []).includes(user.id))); }
function affectedEntries(user, start, end) { return scheduleForUser(user, start, end); }
function assignmentsFor(teacherId, dates) { return db.requests.flatMap(r => (r.assignments || []).filter(a => a.teacherId === teacherId && dates.includes(a.date) && r.status !== 'rejected').map(a => ({ ...a, requestId: r.id }))); }
function recommendationsFor(request) {
  const school = db.schools.find(s => s.id === request.schoolId); const dates = datesBetween(request.startDate, request.endDate); const entries = request.affectedEntries || []; const teachers = db.users.filter(u => u.schoolId === request.schoolId && ['teacher', 'admin'].includes(u.role) && u.id !== request.requesterId && !u.disabled);
  return entries.map(entry => {
    const dayDates = dates.filter(d => weekday(d) === Number(entry.day));
    const candidates = teachers.map(teacher => {
      const unavailable = (teacher.preferences?.unavailableDates || []).filter(d => dayDates.includes(d));
      const timetableConflict = db.timetable.some(e => e.teacherId === teacher.id && e.schoolId === request.schoolId && Number(e.day) === Number(entry.day) && rangesOverlap(entry.start, entry.end, e.start, e.end));
      const coverConflict = assignmentsFor(teacher.id, dayDates).some(a => rangesOverlap(entry.start, entry.end, a.start, a.end));
      const weekCovers = db.requests.flatMap(r => r.assignments || []).filter(a => a.teacherId === teacher.id).length;
      const hardWarnings = []; if (unavailable.length) hardWarnings.push('Marked unavailable'); if (timetableConflict) hardWarnings.push('Teaching at this time'); if (coverConflict) hardWarnings.push('Already covering at this time'); if (weekCovers >= (school?.maxWeeklyCover ?? 8)) hardWarnings.push('Weekly cover limit reached');
      const sameSubject = teacher.preferences?.subjects?.map(s => s.toLowerCase()).includes(entry.subject.toLowerCase());
      const grade = teacher.preferences?.grades?.includes(entry.className.match(/\d+/)?.[0]);
      const prior = db.requests.flatMap(r => r.assignments || []).filter(a => a.teacherId === teacher.id && a.subject === entry.subject).length;
      const score = Math.max(0, 100 - weekCovers * 7 + (sameSubject ? 15 : 0) + (grade ? 7 : 0) + Math.min(prior * 3, 9));
      return { teacherId: teacher.id, name: teacher.name, score, hardWarnings, reasons: [`${weekCovers} cover ${weekCovers === 1 ? 'assignment' : 'assignments'} on record this week`, sameSubject ? 'Subject familiarity' : 'Cross-subject cover is permitted', grade ? 'Grade experience matches' : 'No grade-preference match recorded', prior ? `${prior} prior cover ${prior === 1 ? 'assignment' : 'assignments'} for this subject` : 'No prior cover history for this subject'] };
    }).filter(c => !c.hardWarnings.length).sort((a, b) => b.score - a.score);
    return { entryId: entry.id, className: entry.className, subject: entry.subject, day: entry.day, start: entry.start, end: entry.end, room: entry.room, candidates, warnings: candidates.length ? [] : ['No eligible substitute found without violating a hard scheduling constraint.'] };
  });
}
function csvRows(text) { const rows = []; let row = [], cell = '', quote = false; for (let i = 0; i < text.length; i++) { const ch = text[i]; if (ch === '"') { if (quote && text[i + 1] === '"') { cell += '"'; i++; } else quote = !quote; } else if (ch === ',' && !quote) { row.push(cell.trim()); cell = ''; } else if ((ch === '\n' || ch === '\r') && !quote) { if (ch === '\r' && text[i + 1] === '\n') i++; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = ''; } else cell += ch; } row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows; }
function parseTimetable(text, schoolId) { const rows = csvRows(text); if (rows.length < 2) return { errors: ['The file needs a header row and at least one class entry.'] }; const headers = rows[0].map(h => h.toLowerCase().replace(/\s+/g, '_')); const required = ['day', 'start', 'end', 'class', 'subject', 'teacher_email']; const missing = required.filter(h => !headers.includes(h)); if (missing.length) return { errors: [`Missing required column${missing.length > 1 ? 's' : ''}: ${missing.join(', ')}.`] }; const value = (row, key) => row[headers.indexOf(key)] || ''; const errors = [], entries = [];
  rows.slice(1).forEach((row, index) => { const line = index + 2, teacher = db.users.find(u => u.schoolId === schoolId && u.email.toLowerCase() === value(row, 'teacher_email').toLowerCase()); const student = value(row, 'student_email') ? db.users.find(u => u.schoolId === schoolId && u.email.toLowerCase() === value(row, 'student_email').toLowerCase()) : null; const entry = { id: id('tt_'), schoolId, day: value(row, 'day'), start: value(row, 'start'), end: value(row, 'end'), className: value(row, 'class'), subject: value(row, 'subject'), room: value(row, 'room'), teacherId: teacher?.id, studentIds: student ? [student.id] : [] }; if (!/^[0-6]$/.test(entry.day)) errors.push(`Row ${line}: day must be 0 (Sunday) through 6 (Saturday).`); if (!/^\d{2}:\d{2}$/.test(entry.start) || !/^\d{2}:\d{2}$/.test(entry.end) || entry.start >= entry.end) errors.push(`Row ${line}: use valid 24-hour start and end times.`); if (!teacher) errors.push(`Row ${line}: no teacher account matches ${value(row, 'teacher_email')}.`); if (value(row, 'student_email') && !student) errors.push(`Row ${line}: no student account matches ${value(row, 'student_email')}.`); entries.push(entry); }); return { errors, entries }; }
const contentTypes = { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8' };
function serveStatic(req, res, pathname) { const requested = pathname === '/' ? 'index.html' : pathname.slice(1); const file = path.normalize(path.join(root, requested)); if (!file.startsWith(root) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return error(res, 404, 'Not found.'); res.writeHead(200, { 'Content-Type': contentTypes[path.extname(file)] || 'application/octet-stream' }); fs.createReadStream(file).pipe(res); }

const server = http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host}`); const { pathname } = url; try {
  if (!pathname.startsWith('/api/')) return serveStatic(req, res, pathname);
  if (req.method === 'GET' && pathname === '/api/bootstrap') return json(res, 200, { needsSetup: db.schools.length === 0 });
  if (req.method === 'POST' && pathname === '/api/auth/setup') { if (db.schools.length) return error(res, 409, 'A school is already set up. Sign in instead.'); const body = await readBody(req); const name = clean(body.name), email = clean(body.email).toLowerCase(), schoolName = clean(body.schoolName), password = String(body.password || ''); if (!name || !/^\S+@\S+\.\S+$/.test(email) || schoolName.length < 2 || password.length < 10) return error(res, 422, 'Enter your name, school name, a valid email, and a password of at least 10 characters.'); const code = crypto.randomBytes(4).toString('hex').toUpperCase(); const school = { id: id('s_'), name: schoolName, joinCode: code, maxWeeklyCover: 8, createdAt: now() }; const passwordHash = hash(password), recoveryCode = recovery(); const user = { id: id('u_'), schoolId: school.id, name, email, role: 'admin', passwordHash, recoveryHash: crypto.createHash('sha256').update(recoveryCode).digest('hex'), preferences: { subjects: [], grades: [], unavailableDates: [] }, createdAt: now() }; db.schools.push(school); db.users.push(user); createSession(res, user); save(); return json(res, 201, { user: safeUser(user), school, recoveryCode }); }
  if (req.method === 'POST' && pathname === '/api/auth/signup') { const body = await readBody(req); const name = clean(body.name), email = clean(body.email).toLowerCase(), code = clean(body.joinCode).toUpperCase(), role = clean(body.role), password = String(body.password || ''); const school = db.schools.find(s => s.joinCode === code); if (!school) return error(res, 422, 'That school code was not found.'); if (!['teacher', 'student'].includes(role)) return error(res, 403, 'Public signup is available for teachers and students only.'); if (!name || !/^\S+@\S+\.\S+$/.test(email) || password.length < 10) return error(res, 422, 'Enter your name, a valid email, and a password of at least 10 characters.'); if (db.users.some(u => u.email === email && u.schoolId === school.id)) return error(res, 409, 'An account with that email already exists at this school.'); const recoveryCode = recovery(); const user = { id: id('u_'), schoolId: school.id, name, email, role, passwordHash: hash(password), recoveryHash: crypto.createHash('sha256').update(recoveryCode).digest('hex'), preferences: { subjects: [], grades: [], unavailableDates: [] }, createdAt: now() }; db.users.push(user); createSession(res, user); save(); return json(res, 201, { user: safeUser(user), school, recoveryCode }); }
  if (req.method === 'POST' && pathname === '/api/auth/login') { const body = await readBody(req); const user = db.users.find(u => u.email === clean(body.email).toLowerCase()); if (!user || !verify(String(body.password || ''), user.passwordHash)) return error(res, 401, 'We could not match that email and password.'); if (user.disabled) return error(res, 403, 'This account has been disabled.'); createSession(res, user); return json(res, 200, { user: safeUser(user), school: schoolFor(user) }); }
  if (req.method === 'POST' && pathname === '/api/auth/logout') { const token = parseCookies(req).helio_session; db.sessions = db.sessions.filter(s => s.token !== token); save(); res.setHeader('Set-Cookie', 'helio_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); return json(res, 200, { ok: true }); }
  if (req.method === 'POST' && pathname === '/api/auth/recover') { const body = await readBody(req), user = db.users.find(u => u.email === clean(body.email).toLowerCase()); if (!user || crypto.createHash('sha256').update(String(body.recoveryCode || '')).digest('hex') !== user.recoveryHash) return error(res, 401, 'That recovery code is not valid.'); if (String(body.password || '').length < 10) return error(res, 422, 'Choose a password with at least 10 characters.'); user.passwordHash = hash(body.password); db.sessions = db.sessions.filter(s => s.userId !== user.id); save(); return json(res, 200, { ok: true }); }
  if (req.method === 'GET' && pathname === '/api/me') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { user: safeUser(user), school: schoolFor(user), unread: db.notifications.filter(n => n.userId === user.id && !n.readAt).length }); }
  if (req.method === 'PATCH' && pathname === '/api/me') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); if (body.name) user.name = clean(body.name); if (body.preferences) user.preferences = { ...user.preferences, ...body.preferences }; if (body.currentPassword || body.newPassword) { if (!verify(String(body.currentPassword || ''), user.passwordHash)) return error(res, 401, 'Your current password is incorrect.'); if (String(body.newPassword || '').length < 10) return error(res, 422, 'Your new password must be at least 10 characters.'); user.passwordHash = hash(body.newPassword); } save(); return json(res, 200, { user: safeUser(user) }); }
  if (req.method === 'GET' && pathname === '/api/users') { const user = requireUser(req, res, ['admin']); if (!user) return; return json(res, 200, { users: db.users.filter(u => u.schoolId === user.schoolId).map(safeUser) }); }
  if (req.method === 'POST' && pathname === '/api/users') { const admin = requireUser(req, res, ['admin']); if (!admin) return; const body = await readBody(req), name = clean(body.name), email = clean(body.email).toLowerCase(), role = clean(body.role), password = String(body.password || ''); if (!['admin', 'teacher', 'student'].includes(role) || !name || !/^\S+@\S+\.\S+$/.test(email) || password.length < 10) return error(res, 422, 'Supply a name, valid email, supported role, and 10-character password.'); if (db.users.some(u => u.schoolId === admin.schoolId && u.email === email)) return error(res, 409, 'That email already belongs to this school.'); const recoveryCode = recovery(), user = { id: id('u_'), schoolId: admin.schoolId, name, email, role, passwordHash: hash(password), recoveryHash: crypto.createHash('sha256').update(recoveryCode).digest('hex'), preferences: { subjects: [], grades: [], unavailableDates: [] }, createdAt: now() }; db.users.push(user); save(); return json(res, 201, { user: safeUser(user), recoveryCode }); }
  if (req.method === 'PATCH' && pathname === '/api/school') { const admin = requireUser(req, res, ['admin']); if (!admin) return; const body = await readBody(req), max = Number(body.maxWeeklyCover), school = schoolFor(admin); if (!Number.isInteger(max) || max < 1 || max > 100) return error(res, 422, 'Set a whole-number weekly cover limit between 1 and 100.'); school.maxWeeklyCover = max; save(); return json(res, 200, { school }); }
  if (req.method === 'GET' && pathname === '/api/timetable') { const user = requireUser(req, res); if (!user) return; const entries = db.timetable.filter(e => e.schoolId === user.schoolId && (user.role === 'admin' || e.teacherId === user.id || (e.studentIds || []).includes(user.id))); return json(res, 200, { entries, users: user.role === 'admin' ? db.users.filter(u => u.schoolId === user.schoolId).map(safeUser) : [] }); }
  if (req.method === 'POST' && pathname === '/api/timetable/import') { const user = requireUser(req, res, ['admin']); if (!user) return; const body = await readBody(req), parsed = parseTimetable(String(body.csv || ''), user.schoolId); if (parsed.errors.length) return error(res, 422, 'Your timetable could not be imported.', parsed.errors); const conflicts = []; for (const entry of parsed.entries) { for (const existing of [...db.timetable, ...parsed.entries.filter(e => e !== entry)]) if (existing.id !== entry.id && existing.teacherId === entry.teacherId && existing.day === entry.day && rangesOverlap(entry.start, entry.end, existing.start, existing.end)) conflicts.push(`${entry.className} conflicts with ${existing.className} for the assigned teacher on day ${entry.day}.`); } if (conflicts.length) return error(res, 409, 'The import contains teacher timetable conflicts.', [...new Set(conflicts)]); db.timetable.push(...parsed.entries); save(); return json(res, 201, { imported: parsed.entries.length }); }
  if (req.method === 'POST' && pathname === '/api/timetable') { const admin = requireUser(req, res, ['admin']); if (!admin) return; const body = await readBody(req); const teacher = db.users.find(u => u.id === body.teacherId && u.schoolId === admin.schoolId); const entry = { id: id('tt_'), schoolId: admin.schoolId, day: clean(body.day), start: clean(body.start), end: clean(body.end), className: clean(body.className), subject: clean(body.subject), room: clean(body.room), teacherId: teacher?.id, studentIds: Array.isArray(body.studentIds) ? body.studentIds.filter(v => db.users.some(u => u.id === v && u.schoolId === admin.schoolId && u.role === 'student')) : [] }; if (!teacher || !/^[0-6]$/.test(entry.day) || !entry.className || !entry.subject || !/^\d\d:\d\d$/.test(entry.start) || entry.start >= entry.end) return error(res, 422, 'Enter a valid class, subject, teacher, day, and time range.'); if (db.timetable.some(e => e.teacherId === entry.teacherId && e.day === entry.day && rangesOverlap(e.start, e.end, entry.start, entry.end))) return error(res, 409, 'That teacher already has a class during this time.'); db.timetable.push(entry); save(); return json(res, 201, { entry }); }
  if (req.method === 'GET' && pathname === '/api/requests') { const user = requireUser(req, res); if (!user) return; const requests = db.requests.filter(r => r.schoolId === user.schoolId && (user.role === 'admin' || r.requesterId === user.id || (r.assignments || []).some(a => a.teacherId === user.id))).map(r => ({ ...r, requester: safeUser(db.users.find(u => u.id === r.requesterId)), reviewer: r.reviewerId ? safeUser(db.users.find(u => u.id === r.reviewerId)) : null, assignments: (r.assignments || []).map(a => ({ ...a, teacher: safeUser(db.users.find(u => u.id === a.teacherId)) })) })); return json(res, 200, { requests }); }
  if (req.method === 'POST' && pathname === '/api/requests') { const user = requireUser(req, res, ['teacher', 'student']); if (!user) return; const body = await readBody(req), startDate = clean(body.startDate), endDate = clean(body.endDate), reason = clean(body.reason); if (!/^\d{4}-\d{2}-\d{2}$/.test(startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(endDate) || endDate < startDate) return error(res, 422, 'Choose a valid start and end date.'); if (datesBetween(startDate, endDate).length > 31) return error(res, 422, 'Requests can cover up to 31 days at a time.'); const affected = affectedEntries(user, startDate, endDate); if (!affected.length) return error(res, 422, 'No scheduled classes were found for those dates. Update the timetable or choose different dates.'); const duplicate = db.requests.find(r => r.requesterId === user.id && r.startDate === startDate && r.endDate === endDate && ['submitted', 'in_review', 'approved'].includes(r.status)); if (duplicate) return error(res, 409, 'You already have an active request for those dates.'); const request = { id: id('lr_'), schoolId: user.schoolId, requesterId: user.id, requesterRole: user.role, startDate, endDate, reason, supportingInfo: clean(body.supportingInfo), affectedEntries: affected, status: 'submitted', assignments: [], createdAt: now(), updatedAt: now() }; request.recommendations = user.role === 'teacher' ? recommendationsFor(request) : []; db.requests.unshift(request); const admins = db.users.filter(u => u.schoolId === user.schoolId && u.role === 'admin').map(u => u.id); notify(admins, 'request_submitted', `${user.name} submitted a leave request.`, request.id); save(); return json(res, 201, { request }); }
  const requestMatch = pathname.match(/^\/api\/requests\/([^/]+)(?:\/(recommendations|assignment|decision|messages))?$/);
  if (requestMatch) { const user = requireUser(req, res); if (!user) return; const request = db.requests.find(r => r.id === requestMatch[1] && r.schoolId === user.schoolId); if (!request) return error(res, 404, 'Leave request not found.'); const action = requestMatch[2]; const isParticipant = user.role === 'admin' || request.requesterId === user.id || (request.assignments || []).some(a => a.teacherId === user.id);
    if (!isParticipant) return error(res, 403, 'You cannot access this request.');
    if (req.method === 'GET' && !action) return json(res, 200, { request, messages: db.messages.filter(m => m.requestId === request.id).map(m => ({ ...m, author: safeUser(db.users.find(u => u.id === m.authorId)) })) });
    if (req.method === 'POST' && action === 'recommendations') { if (user.role !== 'admin') return error(res, 403, 'Only administrators can refresh recommendations.'); request.recommendations = recommendationsFor(request); request.updatedAt = now(); save(); return json(res, 200, { recommendations: request.recommendations }); }
    if (req.method === 'POST' && action === 'assignment') { if (user.role !== 'admin') return error(res, 403, 'Only administrators can assign cover.'); const body = await readBody(req); const item = request.recommendations?.find(r => r.entryId === body.entryId); const candidate = item?.candidates?.find(c => c.teacherId === body.teacherId); if (!item || !candidate) return error(res, 422, 'That substitute is no longer eligible. Refresh recommendations and try again.'); const dates = datesBetween(request.startDate, request.endDate).filter(d => weekday(d) === Number(item.day)); const teacher = db.users.find(u => u.id === candidate.teacherId); if (!teacher || (teacher.preferences?.unavailableDates || []).some(d => dates.includes(d)) || db.timetable.some(e => e.teacherId === teacher.id && Number(e.day) === Number(item.day) && rangesOverlap(item.start, item.end, e.start, e.end)) || assignmentsFor(teacher.id, dates).some(a => rangesOverlap(item.start, item.end, a.start, a.end))) return error(res, 409, 'That teacher is no longer available for this cover.'); request.assignments = request.assignments.filter(a => a.entryId !== item.entryId); for (const date of dates) request.assignments.push({ entryId: item.entryId, teacherId: teacher.id, date, className: item.className, subject: item.subject, start: item.start, end: item.end, assignedAt: now(), assignedBy: user.id }); request.status = 'in_review'; request.updatedAt = now(); notify([teacher.id], 'cover_assigned', `You have been proposed to cover ${item.className}.`, request.id); save(); return json(res, 200, { request }); }
    if (req.method === 'POST' && action === 'decision') { if (user.role !== 'admin') return error(res, 403, 'Only administrators can resolve leave requests.'); const body = await readBody(req); if (!['approved', 'rejected'].includes(body.status)) return error(res, 422, 'Choose approve or reject.'); const required = request.affectedEntries.filter(e => datesBetween(request.startDate, request.endDate).some(d => weekday(d) === Number(e.day))).map(e => e.id); if (body.status === 'approved' && request.requesterRole === 'teacher' && required.some(entryId => !request.assignments.some(a => a.entryId === entryId))) return error(res, 422, 'Assign a substitute for every affected class before approving.'); request.status = body.status; request.resolutionNote = clean(body.note); request.reviewerId = user.id; request.updatedAt = now(); notify([request.requesterId, ...request.assignments.map(a => a.teacherId)], `request_${body.status}`, `${user.name} ${body.status} your leave request.`, request.id); save(); return json(res, 200, { request }); }
    if (req.method === 'GET' && action === 'messages') return json(res, 200, { messages: db.messages.filter(m => m.requestId === request.id).map(m => ({ ...m, author: safeUser(db.users.find(u => u.id === m.authorId)) })) });
    if (req.method === 'POST' && action === 'messages') { const body = await readBody(req), text = clean(body.text); if (!text || text.length > 2000) return error(res, 422, 'Messages must be between 1 and 2,000 characters.'); const message = { id: id('m_'), requestId: request.id, authorId: user.id, text, createdAt: now() }; db.messages.push(message); const recipients = [request.requesterId, ...db.users.filter(u => u.schoolId === user.schoolId && u.role === 'admin').map(u => u.id), ...request.assignments.map(a => a.teacherId)].filter(v => v !== user.id); notify(recipients, 'request_message', `${user.name} sent a message about a leave request.`, request.id); save(); return json(res, 201, { message: { ...message, author: safeUser(user) } }); }
  }
  if (req.method === 'GET' && pathname === '/api/notifications') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { notifications: db.notifications.filter(n => n.userId === user.id).slice(0, 30) }); }
  if (req.method === 'POST' && pathname === '/api/notifications/read') { const user = requireUser(req, res); if (!user) return; db.notifications.filter(n => n.userId === user.id && !n.readAt).forEach(n => n.readAt = now()); save(); return json(res, 200, { ok: true }); }
  if (req.method === 'GET' && pathname === '/api/resources') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { resources: db.resources.filter(r => r.schoolId === user.schoolId) }); }
  if (req.method === 'POST' && pathname === '/api/resources') { const user = requireUser(req, res, ['teacher', 'admin']); if (!user) return; const body = await readBody(req), name = clean(body.name), data = String(body.data || ''); if (!name || !data.startsWith('data:') || data.length > 6_000_000) return error(res, 422, 'Choose a named file smaller than 4 MB.'); const [header, encoded] = data.split(','); const mime = header.match(/^data:([^;]+);base64$/)?.[1]; if (!mime || !encoded) return error(res, 422, 'The upload was not recognised.'); const resource = { id: id('r_'), schoolId: user.schoolId, ownerId: user.id, name, mime, className: clean(body.className), createdAt: now() }; fs.writeFileSync(path.join(uploadsDir, resource.id), Buffer.from(encoded, 'base64')); db.resources.unshift(resource); save(); return json(res, 201, { resource }); }
  if (req.method === 'GET' && pathname.startsWith('/api/resources/')) { const user = requireUser(req, res); if (!user) return; const resource = db.resources.find(r => r.id === pathname.split('/').pop() && r.schoolId === user.schoolId); if (!resource) return error(res, 404, 'Resource not found.'); res.writeHead(200, { 'Content-Type': resource.mime, 'Content-Disposition': `attachment; filename="${resource.name.replaceAll('"', '')}"` }); return fs.createReadStream(path.join(uploadsDir, resource.id)).pipe(res); }
  return error(res, 404, 'API route not found.');
} catch (err) { console.error(err); return error(res, err.message === 'Payload too large' ? 413 : 400, err.message || 'Something went wrong.'); } });
server.listen(process.env.PORT || 3000, () => console.log(`Helio running at http://localhost:${process.env.PORT || 3000}`));
